var collectionItemTemplate=
		'<div class="collection-album-container column fourth">'
	  + '	<img src="assets/images/album_covers/01.png">'
		+ '	<div class="collection-album-info caption">'
		+ '		<p>'
		+ '			<a class="album-name" href="/album.html"> The Colours </a>'
		+ '			<br/>'
		+ '			<a href="/album.html"> Pablo Picaso </a>'
		+ '			<br/>'
		+ '			X songs'
		+ '			<br/>'
		+ '		</p>'
		+ '	</div>'
		+ '</div>'
		;